package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Address {
	private int homeNumber;
	private String street;
	private String town;
	private String postal;
}
