package org.example;

import java.util.List;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Browser.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//



public class Browser {
	private Filter customFilters;
	private FilterService filterService = new FilterService();

	public Filter getCustomFilters() {
		return customFilters;
	}

	public void setCustomFilters(Filter customFilters) {
		this.customFilters = customFilters;
	}

	private List<Product> collectResults(Filter filter) {
		List<Product> results;
		if (filter instanceof ManagerFilter mf) {
			results = filterService.applyManagerFilter(mf);
		} else if (filter instanceof ClientFilter cf) {
			results = filterService.applyClientFilter(cf);
		} else {
			results = filterService.applyFilter(filter);
		}
		return results;
	}

	public List<Product> browse(Filter filter) {
		return collectResults(filter);
	}

	public void browseAndDisplay(Filter filter) {
		List<Product> results = collectResults(filter);
		if (results.isEmpty()) {
			System.out.println("No products found.");
		} else {
			System.out.println("=== PRODUCTS (" + results.size() + ") ===");
			for (Product p : results) {
				System.out.println(p);
			}
			System.out.println("========================");
		}
	}

	public void display(String message) {
		System.out.println(message);
	}
}
