package org.example;

import java.util.List;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Browser.java
//  @ Date : 24.05.2026
//  @ Author :
//
//

public class Browser {
	private Filter customFilters;
	private FilterService filterService = new FilterService();

	public List<Product> browse(Filter filter) {
		customFilters = filter;
		List<Product> results;
		if (filter instanceof ManagerFilter mf) {
			results = filterService.filterManagerProducts(mf);
		} else if (filter instanceof ClientFilter cf) {
			results = filterService.filterClientProducts(cf);
		} else {
			results = filterService.filterProducts(filter);
		}

		if (results.isEmpty()) {
			System.out.println("No products found.");
		} else {
			System.out.println("=== PRODUCTS (" + results.size() + ") ===");
			for (Product p : results) {
				System.out.println(p);
			}
			System.out.println("========================");
		}

		return results;
	}
}
