package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CartItem.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class CartItem {
	private int productID;
	private int count;
}
