package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cart.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Cart {
	private CartItem cartItem;
	private Float total;
}
