package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cart.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


import java.util.List;

public class Cart {
	private List<CartItem> cartItem;
	private Float total;


}
