package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Client {
	private Cart cart;
	private Integer ID;
	private Credentials credetials;
	private Integer transactionIDs;
	private NotificationManager notificationManager;
	private Browser browser;
	public void returnProduct(Transaction transactionID) {
	
	}
	
	public void addToCart(Product product) {
	
	}
	
	public void changeCredentials() {
	
	}
	
	public void buyCart() {
	
	}
}
