package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;



public class Client {
	private final Cart cart = new Cart();
	private final Integer ID;
	private final Credentials credentials;
	private final List<Integer> transactionIDs = new ArrayList<>();
	private final NotificationManager notificationManager = new NotificationManager();
	private final List<Transaction> transactionList = new ArrayList<>();
	private Browser browser;
	private final String salt;
	private String passwordHash;

	public Client(int ID, String password, Credentials credentials) throws NoSuchAlgorithmException {
		this.ID = ID;
		this.salt = generateSalt();
		password = password + salt;
		passwordHash = hash(password);
		this.credentials = credentials;
	}

	public Credentials getCredetials() {
		return credentials;
	}

	public void returnProduct(int transactionID) { //uses "local" transaction ID - from the "POV" of the Client
		Transaction transaction = transactionList.get(transactionID);
		boolean returnRequested = transaction.markForReturn();
		if (returnRequested) Shop.getInstance().notifyManager(
				"Client " + this.getID()
						+ " requested return for transaction " + transactionID
		);
	}

	public Credentials getCredentials() {
		return credentials;
	}

	public void changePassword(String oldpassword, String newpassword) throws Exception {
		if (!hash(oldpassword + salt).equals(passwordHash))
			throw new Exception("Wrong password");
		this.passwordHash = hash(newpassword + salt);
	}
	public void changeEmail(String password, String newEmail) throws Exception {
		if (!hash(password + salt).equals(passwordHash))
			throw new Exception("Wrong password");
		this.getCredetials().setEmail(newEmail);
	}
	public void changeAddress(String password, Integer homeNum, String street, String town, String postal) throws Exception {
		if (!hash(password + salt).equals(passwordHash))
			throw new Exception("Wrong password");
		if (homeNum != null) credentials.getAddress().setHomeNumber(homeNum);
		if (street != null) credentials.getAddress().setStreet(street);
		if (town != null) credentials.getAddress().setTown(town);
		if (postal != null) credentials.getAddress().setPostal(postal);
    }





	public void addToCart(Product product) {
		cart.addProduct(product);
	}



	public void buyCart() {
	
	}



	public Integer getID() {
		return ID;
	}




	public Integer getTransactionIDs() {
		return transactionIDs;
	}

	public void setTransactionIDs(Integer transactionIDs) {
		this.transactionIDs = transactionIDs;
	}

	public NotificationManager getNotificationManager() {
		return notificationManager;
	}

	public void setNotificationManager(NotificationManager notificationManager) {
		this.notificationManager = notificationManager;
	}

	public Browser getBrowser() {
		return browser;
	}

	public void setBrowser(Browser browser) {
		this.browser = browser;
	}

	private static String generateSalt() {
		Random random = new Random();
		StringBuilder salt = new StringBuilder();
		for (int i = 0; i < 16; i++) {
			salt.append((char) (random.nextInt(94) + 33));
		}
		return salt.toString();
	}

	static String hash(String input) throws NoSuchAlgorithmException { //SHA-256
		MessageDigest md = MessageDigest.getInstance("SHA-256");
		byte[] hashed = md.digest(input.getBytes());
		StringBuilder sb = new StringBuilder();
		for (byte b : hashed) {
			sb.append(String.format("%02x", b));
		}
		return sb.toString();
	}
}
