package org.example;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ClientFilter.java
//  @ Date : 24.05.2026
//  @ Author :
//
//

public class ClientFilter extends Filter {
}
