package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Client {
	private Cart cart;
	private Integer ID;
	private Credentials credentials;
	private Integer transactionIDs;
	private NotificationManager notificationManager;
	private Browser browser;

	public Client(int ID, Credentials credentials)
	{
		this.ID = ID;
		this.credentials = credentials;
	}

	public Credentials getCredetials() {
		return credentials;
	}





	public void returnProduct(Transaction transactionID) {



	}
	
	public void addToCart(Product product) {
	
	}
	
	public void changeCredentials() {
	
	}
	
	public void buyCart() {
	
	}

	public Cart getCart() {
		return cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public Integer getID() {
		return ID;
	}

	public void setID(Integer ID) {
		this.ID = ID;
	}

	public Credentials getCredentials() {
		return credentials;
	}

	public void setCredentials(Credentials credentials) {
		this.credentials = credentials;
	}

	public Integer getTransactionIDs() {
		return transactionIDs;
	}

	public void setTransactionIDs(Integer transactionIDs) {
		this.transactionIDs = transactionIDs;
	}

	public NotificationManager getNotificationManager() {
		return notificationManager;
	}

	public void setNotificationManager(NotificationManager notificationManager) {
		this.notificationManager = notificationManager;
	}

	public Browser getBrowser() {
		return browser;
	}

	public void setBrowser(Browser browser) {
		this.browser = browser;
	}
}
