package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ClientFacade.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class ClientFacade {
	Client client;
	public ClientFacade(Client client){
		this.client = client;
	}

	public void returnProduct(int transactionID) { //uses "local" transaction ID - from the "POV" of the Client
		client.returnProduct(transactionID);
	}



	public int browse(ClientFilter filter) {

        return 0;
    }
	
	public void addToCart(Product product) {
	
	}
	
	public void buyCart() {
	
	}


	
	public void changeCredentials() {
	
	}
	
	public void browseNotifications() {
	
	}
}
