package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ClientFacade.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class ClientFacade {
	public int browse(ClientFilter filter) {

        return 0;
    }
	
	public void addToCart(Product product) {
	
	}
	
	public void buyCart() {
	
	}
	
	public void returnProduct(Transaction transactionID) {
	
	}
	
	public void changeCredentials() {
	
	}
	
	public void browseNotifications() {
	
	}
}
