package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Color.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Color {
	public Object CZARNE;
	public Object BIALE;
	public Object CZERWONE;
	public Object ZIELONE;
	public Object POMARANCZOWE;
	public Object NIEBIESKIE;
	public Object FIOLETOWE;
	public Object BRAZOWE;
}
