package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Color.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public enum Color {
	CZARNE,
	 BIALE,
	 CZERWONE,
	 ZIELONE,
	 POMARANCZOWE,
	 NIEBIESKIE,
	 FIOLETOWE,
	 BRAZOWE
}
