package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Credentials.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Credentials {
	private String username;
	private String email;
	private Address address;

	public Credentials(String username, String email, Address address) {
		this.username = username;
		this.email = email;
		this.address = address;
	}

	public String getUsername() {
		return username;
	}

	public String getEmail() {
		return email;
	}

	public Address getAddress() {
		return address;
	}
}
