package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Credentials.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Credentials {
	private String username;
	private String password;
	private String email;
	private Address address;
}
