package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FilterService.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class FilterService {
	public int applyClientFilter(ClientFilter f) {
		return 0;
	}
	
	public int applyManagerFilter(ManagerFilter f) {
		return 0;
	}
}
