package org.example;

import java.util.List;
import java.util.stream.Collectors;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FilterService.java
//  @ Date : 24.05.2026
//  @ Author :
//
//

public class FilterService {

	List<Product> filterProducts(Filter f) {
		List<Color> allowedColors = f.getAllowedColors();
		boolean restrictColors = !allowedColors.isEmpty();
		return Shop.getInstance().getProductList().stream()
				.filter(p -> Shop.getInstance().getEffectivePrice(p.getID()) >= f.getLowerBracket())
				.filter(p -> Shop.getInstance().getEffectivePrice(p.getID()) <= f.getUpperBracket())
				.filter(p -> p.getSize() >= f.getSmallestSize())
				.filter(p -> p.getSize() <= f.getBiggestSize())
				.filter(p -> !restrictColors || (p.getColor() != null && allowedColors.contains(p.getColor())))
				.filter(p -> !f.isOnSale() || Shop.getInstance().isProductOnSale(p.getID()))
				.filter(p -> !f.isDisplaySecondHand() || (p instanceof UsedProduct))
				.collect(Collectors.toList());
	}

	List<Product> filterClientProducts(ClientFilter f) {
		return filterProducts(f);
	}

	List<Product> filterManagerProducts(ManagerFilter f) {
		List<Product> results = filterProducts(f);
		if (f.getLowstockthreshold() > 0) {
			results = results.stream()
					.filter(p -> p.getCount() <= f.getLowstockthreshold())
					.collect(Collectors.toList());
		}
		return results;
	}

}
