package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Filter.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Filter {
	private boolean isOnSale;
	private float lowerBracket;
	private float upperBracket;
	private boolean displaySecondHand;
	private int smallestSize;
	private int biggestSize;
	private Color allowedColors;
}
