package org.example;
import java.util.List;
import java.util.stream.Collectors;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FilterService.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//



public class FilterService {

	public List<Product> applyFilter(Filter f) {
		return Shop.getInstance().getProductList().stream()
				.filter(p -> Shop.getInstance().getEffectivePrice(p.getID()) >= f.getLowerBracket())
				.filter(p -> Shop.getInstance().getEffectivePrice(p.getID()) <= f.getUpperBracket())
				.filter(p -> p.getSize() >= f.getSmallestSize())
				.filter(p -> p.getSize() <= f.getBiggestSize())
				.filter(p -> f.getAllowedColors() == null || f.getAllowedColors() == p.getColor())
				.filter(p -> !f.isOnSale() || Shop.getInstance().isProductOnSale(p.getID()))
				.filter(p -> !f.isDisplaySecondHand() || (p instanceof UsedProduct))
				.collect(Collectors.toList());
	}

	public List<Product> applyClientFilter(ClientFilter f) {
		return applyFilter(f);
	}

	public List<Product> applyManagerFilter(ManagerFilter f) {
		List<Product> results = applyFilter(f);
		if (f.getLowstockthreshold() > 0) {
			results = results.stream()
					.filter(p -> p.getCount() <= f.getLowstockthreshold())
					.collect(Collectors.toList());
		}
		return results;
	}
}
