package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InAppNotificationSender.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class InAppNotificationSender extends INotificationSender {
	//public void send(Object User recipient, Object Notification n) {
	
	//}
}
