package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : INotificationSender.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class INotificationSender {
	public void send(Notification n) {
	
	}
}
