package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ManagerFilter.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


public class ManagerFilter extends Filter {
	private int lowstockthreshold = 0;

	public int getLowstockthreshold() { return lowstockthreshold; }
	public void setLowstockthreshold(int v) { this.lowstockthreshold = v; }
}
