package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notification.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Notification {
	private int sentDate;
	private int readDate = 0;
	private String contents;
}
