package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notification.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


import java.time.LocalDateTime;

public class Notification {
	private LocalDateTime sentDate;
	private String contents;

    public Notification(LocalDateTime sendDate, String s) {
    	this.sentDate = sendDate;
		this.contents = s;
	}

	public String returnMessageFull() {
		return "========================\n" +
				sentDate + "\n" +
				contents + "\n" +
				"========================" +
				"\n";
	}
}
