package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NotificationManager.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class NotificationManager {
	private Notification notification;
	private ClientFacade delegates;
	public void browseNotifications() {
	
	}
}
