package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Product {
	private int ID;
	private float price;
	private int size;
	private int count;
	private Type type;
	private int lowstockthreshold = 99999;
	private float discount;
}
