package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReturnState.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public enum ReturnState {
	NOTATTEMPTED,
	PENDING,
	RETURNED,
	DENIED
}
