package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sale.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


import java.time.LocalDate;

public class Sale {
	private LocalDate startDate;
	private LocalDate endDate;
	private int discountedPrice;
	private boolean currentlyActive = true;
	private int discountedProductID;
}
