package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shop.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Shop {
	private Product products;
	private Transaction transactions;
	private Client client;
	private Sale saleList;
	public void setPrice() {
	
	}
	
	public void manageSales() {
	
	}
	
	public void deleteAccount(int ID) {
	
	}
	
	public void displayTransactionData(int ID, Filter filter) {
	
	}
	
	public void displayAccountData(int ID) {
	
	}
}
