package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shop.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.util.ArrayList;


public class Shop {
	private static Shop instance = null;
	private static NotificationManager managersManager;
	private Shop() {};
	public static Shop getInstance() {
		if (instance == null) {
			instance = new Shop();
		}
		return instance;
	}

	private ArrayList<Client> clientList = new ArrayList<>();;

	public boolean checkLoginCollision(String username) { // only login and mail are to be avoided for collisions, rest irrelevant
		for(Client client : clientList) {
			if (client.getCredetials().getUsername().equals(username))
				return true;
		}
		return false;
	}
	public boolean checkEmailCollision(String email) { // only login and mail are to be avoided for collisions, rest irrelevant
		for(Client client : clientList) {
			if (client.getCredetials().getEmail().equals(email))
				return true;
		}
		return false;
	}



	public boolean registerClient(String password, Credentials credentials) throws NoSuchAlgorithmException {
		int ID = clientList.size();
		Client createdClient = new Client(ID, password, credentials);
		clientList.add(createdClient);
		return true;
	}

	public void notifyManager(String message) {
		Notification n = new Notification(LocalDateTime.now(), "Client " + t.getUserID() +
				" wants to return transaction " + t.getTransactionID());
		managersManager.addNotification(n);
	}















	private Product products;
	private Transaction transactions;
	private Sale saleList;
	public void setPrice() {
	
	}
	
	public void manageSales() {
	
	}
	
	public void deleteAccount(int ID) {
	
	}
	
	public void displayTransactionData(int ID, Filter filter) {
	
	}
	
	public void displayAccountData(int ID) {
	
	}
}
