package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreManager.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class StoreManager {
//	private Object notificationManager: NotificationManager;
	private Browser browser;
}
