package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreManagerFacade.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class StoreManagerFacade {
	public void setPrice(int productID, float price) {
	
	}
	
	public void manageSales() {
	
	}
	
	public void deleteAccount(int ID) {
	
	}
	
//	public Product[0..*] getLowStockProducts() {
//
//	}
	
	public void displayTransactionData(int ID, ManagerFilter filter) {
	
	}
	
	public void displayAccountData(int ID) {
	
	}
	
	public void browseNotifications() {
	
	}
}
