package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//


import java.time.LocalDate;

public class Transaction {
	private int transactionID;
	private LocalDate date;
	private int productID;
	private ReturnState returnedState = ReturnState.NOTATTEMPTED;
	private LocalDate returnDate;
	private int userID;
}
