package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Type.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class Type {
	public Object SPORTOWE;
	public Object KAPCIE;
	public Object TRAMPKI;
	public Object SANDALY;
	public Object KOZAKI;
	public Object NAOBCASACH;
}
