package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UsedProduct.java
//  @ Date : 24.05.2026
//  @ Author : 
//
//




public class UsedProduct extends Product{
	private int usedID;
	private String defectsDescription;
}
