package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled





public class UsedProduct extends Product{
	private int usedID;
	private String defectsDescription;

	public int getUsedID() {
		return usedID;
	}

	public void setUsedID(int usedID) {
		this.usedID = usedID;
	}

	public String getDefectsDescription() {
		return defectsDescription;
	}

	public void setDefectsDescription(String defectsDescription) {
		this.defectsDescription = defectsDescription;
	}
}
